/*
 *   Copyright © 2025 PSPDFKit GmbH. All rights reserved.
 *
 *   The PSPDFKit Sample applications are licensed with a modified BSD license.
 *   Please see License for details. This notice may not be removed from this file.
 */

package com.pspdfkit.catalog.ui.theming

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF834C76)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFDE9DCC)
val onPrimaryContainerLight = Color(0xFF65325A)
val secondaryLight = Color(0xFF256B38)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFF6EB579)
val onSecondaryContainerLight = Color(0xFF00451B)
val tertiaryLight = Color(0xFF765A00)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFF0C968)
val onTertiaryContainerLight = Color(0xFF6D5300)
val errorLight = Color(0xFFAC2C19)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFCE452E)
val onErrorContainerLight = Color(0xFFFFFBFF)
val backgroundLight = Color(0xFFFFF7F9)
val onBackgroundLight = Color(0xFF1F1A1D)
val surfaceLight = Color(0xFFFDF8F7)
val onSurfaceLight = Color(0xFF1C1B1B)
val surfaceVariantLight = Color(0xFFEBE1D7)
val onSurfaceVariantLight = Color(0xFF4C463F)
val outlineLight = Color(0xFF7D766E)
val outlineVariantLight = Color(0xFFCEC5BC)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF313030)
val inverseOnSurfaceLight = Color(0xFFF4F0EF)
val inversePrimaryLight = Color(0xFFF5B2E2)
val surfaceDimLight = Color(0xFFDDD9D8)
val surfaceBrightLight = Color(0xFFFDF8F7)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF7F3F2)
val surfaceContainerLight = Color(0xFFF1EDEC)
val surfaceContainerHighLight = Color(0xFFEBE7E6)
val surfaceContainerHighestLight = Color(0xFFE5E2E1)

val primaryDark = Color(0xFFFCB8E8)
val onPrimaryDark = Color(0xFF4E1E45)
val primaryContainerDark = Color(0xFFDE9DCC)
val onPrimaryContainerDark = Color(0xFF65325A)
val secondaryDark = Color(0xFF8ED798)
val onSecondaryDark = Color(0xFF003915)
val secondaryContainerDark = Color(0xFF6EB579)
val onSecondaryContainerDark = Color(0xFF00451B)
val tertiaryDark = Color(0xFFFFE7B5)
val onTertiaryDark = Color(0xFF3E2E00)
val tertiaryContainerDark = Color(0xFFF0C968)
val onTertiaryContainerDark = Color(0xFF6D5300)
val errorDark = Color(0xFFFFB4A6)
val onErrorDark = Color(0xFF660700)
val errorContainerDark = Color(0xFFF56047)
val onErrorContainerDark = Color(0xFF560500)
val backgroundDark = Color(0xFF171215)
val onBackgroundDark = Color(0xFFEAE0E4)
val surfaceDark = Color(0xFF141313)
val onSurfaceDark = Color(0xFFE5E2E1)
val surfaceVariantDark = Color(0xFF4C463F)
val onSurfaceVariantDark = Color(0xFFCEC5BC)
val outlineDark = Color(0xFF988F87)
val outlineVariantDark = Color(0xFF4C463F)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE5E2E1)
val inverseOnSurfaceDark = Color(0xFF313030)
val inversePrimaryDark = Color(0xFF834C76)
val surfaceDimDark = Color(0xFF141313)
val surfaceBrightDark = Color(0xFF3A3938)
val surfaceContainerLowestDark = Color(0xFF0E0E0E)
val surfaceContainerLowDark = Color(0xFF1C1B1B)
val surfaceContainerDark = Color(0xFF201F1F)
val surfaceContainerHighDark = Color(0xFF2B2A29)
val surfaceContainerHighestDark = Color(0xFF363434)
